"""empty message

Revision ID: 0408386dabfc
Revises: 60fb6d61a38d
Create Date: 2024-12-07 21:27:38.684833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0408386dabfc'
down_revision: Union[str, None] = '60fb6d61a38d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients__api_clients', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.drop_index('ix_clients__api_clients_is_active', table_name='clients__api_clients')
    op.create_index(op.f('ix_clients__api_clients_disabled'), 'clients__api_clients', ['disabled'], unique=False)
    op.drop_column('clients__api_clients', 'is_active')
    op.add_column('clients__api_keys', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_index('ix_clients__api_keys_is_active', table_name='clients__api_keys')
    op.create_index(op.f('ix_clients__api_keys_active'), 'clients__api_keys', ['active'], unique=False)
    op.drop_column('clients__api_keys', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients__api_keys', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clients__api_keys_active'), table_name='clients__api_keys')
    op.create_index('ix_clients__api_keys_is_active', 'clients__api_keys', ['is_active'], unique=False)
    op.drop_column('clients__api_keys', 'active')
    op.add_column('clients__api_clients', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clients__api_clients_disabled'), table_name='clients__api_clients')
    op.create_index('ix_clients__api_clients_is_active', 'clients__api_clients', ['is_active'], unique=False)
    op.drop_column('clients__api_clients', 'disabled')
    # ### end Alembic commands ###
