"""empty message

Revision ID: 09a700243f83
Revises: bfb0f184ace1
Create Date: 2025-03-31 03:54:57.761699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a700243f83'
down_revision: Union[str, None] = 'bfb0f184ace1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes__questions', sa.Column('correct_option_index', sa.Integer(), nullable=False))
    op.drop_column('quizzes__questions', 'correct_option')
    op.add_column('quizzes__quiz_attempt_question_answers', sa.Column('is_correct', sa.Boolean(), nullable=False))
    op.drop_index('ix_quizzes__quiz_attempt_question_answers_correct', table_name='quizzes__quiz_attempt_question_answers')
    op.create_index(op.f('ix_quizzes__quiz_attempt_question_answers_is_correct'), 'quizzes__quiz_attempt_question_answers', ['is_correct'], unique=False)
    op.drop_column('quizzes__quiz_attempt_question_answers', 'correct')
    op.add_column('quizzes__quiz_attempts', sa.Column('submitted', sa.Boolean(), nullable=False))
    op.add_column('quizzes__quiz_attempts', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_quizzes__quiz_attempts_submitted'), 'quizzes__quiz_attempts', ['submitted'], unique=False)
    op.add_column('quizzes__quizzes', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('quizzes__quizzes', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('quizzes__quizzes', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.drop_index('ix_quizzes__quizzes_name', table_name='quizzes__quizzes')
    op.drop_constraint('quizzes__quizzes_name_created_by_id_key', 'quizzes__quizzes', type_='unique')
    op.create_index(op.f('ix_quizzes__quizzes_is_public'), 'quizzes__quizzes', ['is_public'], unique=False)
    op.create_index(op.f('ix_quizzes__quizzes_title'), 'quizzes__quizzes', ['title'], unique=False)
    op.create_unique_constraint(None, 'quizzes__quizzes', ['title', 'created_by_id'])
    op.drop_column('quizzes__quizzes', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes__quizzes', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quizzes__quizzes', type_='unique')
    op.drop_index(op.f('ix_quizzes__quizzes_title'), table_name='quizzes__quizzes')
    op.drop_index(op.f('ix_quizzes__quizzes_is_public'), table_name='quizzes__quizzes')
    op.create_unique_constraint('quizzes__quizzes_name_created_by_id_key', 'quizzes__quizzes', ['name', 'created_by_id'])
    op.create_index('ix_quizzes__quizzes_name', 'quizzes__quizzes', ['name'], unique=False)
    op.drop_column('quizzes__quizzes', 'is_public')
    op.drop_column('quizzes__quizzes', 'duration')
    op.drop_column('quizzes__quizzes', 'title')
    op.drop_index(op.f('ix_quizzes__quiz_attempts_submitted'), table_name='quizzes__quiz_attempts')
    op.drop_column('quizzes__quiz_attempts', 'submitted_at')
    op.drop_column('quizzes__quiz_attempts', 'submitted')
    op.add_column('quizzes__quiz_attempt_question_answers', sa.Column('correct', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_quizzes__quiz_attempt_question_answers_is_correct'), table_name='quizzes__quiz_attempt_question_answers')
    op.create_index('ix_quizzes__quiz_attempt_question_answers_correct', 'quizzes__quiz_attempt_question_answers', ['correct'], unique=False)
    op.drop_column('quizzes__quiz_attempt_question_answers', 'is_correct')
    op.add_column('quizzes__questions', sa.Column('correct_option', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('quizzes__questions', 'correct_option_index')
    # ### end Alembic commands ###
