"""empty message

Revision ID: 09d036ccafe8
Revises: d7767ddcca25
Create Date: 2025-04-21 22:31:01.470631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d036ccafe8'
down_revision: Union[str, None] = 'd7767ddcca25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts__client_accounts', sa.Column('deleted_by_id', sa.UUID(), nullable=True))
    op.add_column('accounts__client_accounts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'accounts__client_accounts', 'accounts__client_accounts', ['deleted_by_id'], ['id'])
    op.add_column('clients__api_clients', sa.Column('is_disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('clients__api_clients', sa.Column('deleted_by_id', sa.UUID(), nullable=True))
    op.add_column('clients__api_clients', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_clients__api_clients_disabled', table_name='clients__api_clients')
    op.create_index(op.f('ix_clients__api_clients_is_disabled'), 'clients__api_clients', ['is_disabled'], unique=False)
    op.create_foreign_key(None, 'clients__api_clients', 'accounts__client_accounts', ['deleted_by_id'], ['id'])
    op.drop_column('clients__api_clients', 'disabled')
    op.add_column('quizzes__questions', sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('quizzes__questions', sa.Column('is_latest', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('quizzes__questions', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('quizzes__questions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quizzes__questions', sa.Column('deleted_by_id', sa.UUID(), nullable=True))
    op.drop_index('ix_quizzes__questions_uid', table_name='quizzes__questions')
    op.create_index(op.f('ix_quizzes__questions_uid'), 'quizzes__questions', ['uid'], unique=False)
    op.create_index(op.f('ix_quizzes__questions_created_by_id'), 'quizzes__questions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_quizzes__questions_is_latest'), 'quizzes__questions', ['is_latest'], unique=False)
    op.create_unique_constraint('uq_question_uid_version', 'quizzes__questions', ['uid', 'version'])
    op.create_foreign_key(None, 'quizzes__questions', 'accounts__client_accounts', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'quizzes__questions', 'accounts__client_accounts', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_quiz_atmpt_questn_answr_quiz_questn_answrd_by_id_ctd_at', table_name='quizzes__quiz_attempt_question_answers')
    op.drop_index('ix_quizzes__quiz_attempt_question_answers_quiz_id', table_name='quizzes__quiz_attempt_question_answers')
    op.create_index('ix_quiz_atmpt_questn_answr_questn_answrd_by_id_ctd_at', 'quizzes__quiz_attempt_question_answers', ['question_id', 'answered_by_id', 'created_at'], unique=False)
    op.drop_constraint('quizzes__quiz_attempt_question_answers_quiz_id_fkey', 'quizzes__quiz_attempt_question_answers', type_='foreignkey')
    op.drop_column('quizzes__quiz_attempt_question_answers', 'quiz_id')
    op.add_column('quizzes__quiz_attempts', sa.Column('is_submitted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('quizzes__quiz_attempts', 'duration',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.drop_index('ix_quizzes__quiz_attempts_submitted', table_name='quizzes__quiz_attempts')
    op.create_index(op.f('ix_quizzes__quiz_attempts_is_submitted'), 'quizzes__quiz_attempts', ['is_submitted'], unique=False)
    op.drop_column('quizzes__quiz_attempts', 'submitted')
    op.add_column('quizzes__quizzes', sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('quizzes__quizzes', sa.Column('is_latest', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('quizzes__quizzes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quizzes__quizzes', sa.Column('deleted_by_id', sa.UUID(), nullable=True))
    op.alter_column('quizzes__quizzes', 'duration',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.drop_index('ix_quizzes__quizzes_uid', table_name='quizzes__quizzes')
    op.create_index(op.f('ix_quizzes__quizzes_uid'), 'quizzes__quizzes', ['uid'], unique=False)
    op.create_index(op.f('ix_quizzes__quizzes_is_latest'), 'quizzes__quizzes', ['is_latest'], unique=False)
    op.create_unique_constraint('uq_quiz_uid_version', 'quizzes__quizzes', ['uid', 'version'])
    op.create_foreign_key(None, 'quizzes__quizzes', 'accounts__client_accounts', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('search__search_records', sa.Column('deleted_by_id', sa.UUID(), nullable=True))
    op.add_column('search__search_records', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'search__search_records', 'accounts__client_accounts', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('search__term_sources', sa.Column('deleted_by_id', sa.UUID(), nullable=True))
    op.add_column('search__term_sources', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'search__term_sources', 'accounts__client_accounts', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('search__terms', sa.Column('deleted_by_id', sa.UUID(), nullable=True))
    op.add_column('search__terms', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'search__terms', 'accounts__client_accounts', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('search__topics', sa.Column('deleted_by_id', sa.UUID(), nullable=True))
    op.add_column('search__topics', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'search__topics', 'accounts__client_accounts', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search__topics', type_='foreignkey')
    op.drop_column('search__topics', 'deleted_at')
    op.drop_column('search__topics', 'deleted_by_id')
    op.drop_constraint(None, 'search__terms', type_='foreignkey')
    op.drop_column('search__terms', 'deleted_at')
    op.drop_column('search__terms', 'deleted_by_id')
    op.drop_constraint(None, 'search__term_sources', type_='foreignkey')
    op.drop_column('search__term_sources', 'deleted_at')
    op.drop_column('search__term_sources', 'deleted_by_id')
    op.drop_constraint(None, 'search__search_records', type_='foreignkey')
    op.drop_column('search__search_records', 'deleted_at')
    op.drop_column('search__search_records', 'deleted_by_id')
    op.drop_constraint(None, 'quizzes__quizzes', type_='foreignkey')
    op.drop_constraint('uq_quiz_uid_version', 'quizzes__quizzes', type_='unique')
    op.drop_index(op.f('ix_quizzes__quizzes_is_latest'), table_name='quizzes__quizzes')
    op.drop_index(op.f('ix_quizzes__quizzes_uid'), table_name='quizzes__quizzes')
    op.create_index('ix_quizzes__quizzes_uid', 'quizzes__quizzes', ['uid'], unique=True)
    op.alter_column('quizzes__quizzes', 'duration',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('quizzes__quizzes', 'deleted_by_id')
    op.drop_column('quizzes__quizzes', 'deleted_at')
    op.drop_column('quizzes__quizzes', 'is_latest')
    op.drop_column('quizzes__quizzes', 'version')
    op.add_column('quizzes__quiz_attempts', sa.Column('submitted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_quizzes__quiz_attempts_is_submitted'), table_name='quizzes__quiz_attempts')
    op.create_index('ix_quizzes__quiz_attempts_submitted', 'quizzes__quiz_attempts', ['submitted'], unique=False)
    op.alter_column('quizzes__quiz_attempts', 'duration',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('quizzes__quiz_attempts', 'is_submitted')
    op.add_column('quizzes__quiz_attempt_question_answers', sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('quizzes__quiz_attempt_question_answers_quiz_id_fkey', 'quizzes__quiz_attempt_question_answers', 'quizzes__quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_quiz_atmpt_questn_answr_questn_answrd_by_id_ctd_at', table_name='quizzes__quiz_attempt_question_answers')
    op.create_index('ix_quizzes__quiz_attempt_question_answers_quiz_id', 'quizzes__quiz_attempt_question_answers', ['quiz_id'], unique=False)
    op.create_index('ix_quiz_atmpt_questn_answr_quiz_questn_answrd_by_id_ctd_at', 'quizzes__quiz_attempt_question_answers', ['quiz_id', 'question_id', 'answered_by_id', 'created_at'], unique=False)
    op.drop_constraint(None, 'quizzes__questions', type_='foreignkey')
    op.drop_constraint(None, 'quizzes__questions', type_='foreignkey')
    op.drop_constraint('uq_question_uid_version', 'quizzes__questions', type_='unique')
    op.drop_index(op.f('ix_quizzes__questions_is_latest'), table_name='quizzes__questions')
    op.drop_index(op.f('ix_quizzes__questions_created_by_id'), table_name='quizzes__questions')
    op.drop_index(op.f('ix_quizzes__questions_uid'), table_name='quizzes__questions')
    op.create_index('ix_quizzes__questions_uid', 'quizzes__questions', ['uid'], unique=True)
    op.drop_column('quizzes__questions', 'deleted_by_id')
    op.drop_column('quizzes__questions', 'deleted_at')
    op.drop_column('quizzes__questions', 'created_by_id')
    op.drop_column('quizzes__questions', 'is_latest')
    op.drop_column('quizzes__questions', 'version')
    op.add_column('clients__api_clients', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clients__api_clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients__api_clients_is_disabled'), table_name='clients__api_clients')
    op.create_index('ix_clients__api_clients_disabled', 'clients__api_clients', ['disabled'], unique=False)
    op.drop_column('clients__api_clients', 'deleted_at')
    op.drop_column('clients__api_clients', 'deleted_by_id')
    op.drop_column('clients__api_clients', 'is_disabled')
    op.drop_constraint(None, 'accounts__client_accounts', type_='foreignkey')
    op.drop_column('accounts__client_accounts', 'deleted_at')
    op.drop_column('accounts__client_accounts', 'deleted_by_id')
    # ### end Alembic commands ###
