"""empty message

Revision ID: 0fd91c6fb4ca
Revises: be538051e438
Create Date: 2024-12-06 21:18:21.121299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd91c6fb4ca'
down_revision: Union[str, None] = 'be538051e438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts__client_accounts', 'username')
    op.drop_constraint('clients__api_clients_name_key', 'clients__api_clients', type_='unique')
    op.create_unique_constraint(None, 'clients__api_clients', ['account_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients__api_clients', type_='unique')
    op.create_unique_constraint('clients__api_clients_name_key', 'clients__api_clients', ['name'])
    op.add_column('accounts__client_accounts', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
