"""empty message

Revision ID: 1c86900b55d6
Revises: 5ede32348981
Create Date: 2024-12-24 11:44:02.629498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c86900b55d6'
down_revision: Union[str, None] = '5ede32348981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search__glossary_metrics_id', table_name='search__glossary_metrics')
    op.drop_table('search__glossary_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search__glossary_metrics',
    sa.Column('term_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('search_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('verified_term_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unverified_term_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('most_searched_queries', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('most_searched_topics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='search__glossary_metrics_pkey')
    )
    op.create_index('ix_search__glossary_metrics_id', 'search__glossary_metrics', ['id'], unique=False)
    # ### end Alembic commands ###
