"""empty message

Revision ID: 280a2e931e07
Revises: aa625e423004
Create Date: 2024-12-18 11:29:33.498497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280a2e931e07'
down_revision: Union[str, None] = 'aa625e423004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search__search_records', sa.Column('extradata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search__search_records', 'extradata')
    # ### end Alembic commands ###
