"""empty message

Revision ID: 282bc349897c
Revises: beabaa47d346
Create Date: 2025-03-08 13:48:08.450217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282bc349897c'
down_revision: Union[str, None] = 'beabaa47d346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits__audit_log_entries', sa.Column('actor_uid', sa.String(length=50), nullable=True))
    op.add_column('audits__audit_log_entries', sa.Column('account_uid', sa.String(length=50), nullable=True))
    op.add_column('audits__audit_log_entries', sa.Column('target_uid', sa.String(length=50), nullable=True))
    op.drop_index('ix_audits__audit_log_entries_account_id', table_name='audits__audit_log_entries')
    op.drop_index('ix_audits__audit_log_entries_actor_id', table_name='audits__audit_log_entries')
    op.drop_index('ix_audits__audit_log_entries_target_id', table_name='audits__audit_log_entries')
    op.create_index(op.f('ix_audits__audit_log_entries_account_uid'), 'audits__audit_log_entries', ['account_uid'], unique=False)
    op.create_index(op.f('ix_audits__audit_log_entries_actor_uid'), 'audits__audit_log_entries', ['actor_uid'], unique=False)
    op.create_index(op.f('ix_audits__audit_log_entries_target_uid'), 'audits__audit_log_entries', ['target_uid'], unique=False)
    op.drop_column('audits__audit_log_entries', 'target_id')
    op.drop_column('audits__audit_log_entries', 'actor_id')
    op.drop_column('audits__audit_log_entries', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits__audit_log_entries', sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('audits__audit_log_entries', sa.Column('actor_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('audits__audit_log_entries', sa.Column('target_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audits__audit_log_entries_target_uid'), table_name='audits__audit_log_entries')
    op.drop_index(op.f('ix_audits__audit_log_entries_actor_uid'), table_name='audits__audit_log_entries')
    op.drop_index(op.f('ix_audits__audit_log_entries_account_uid'), table_name='audits__audit_log_entries')
    op.create_index('ix_audits__audit_log_entries_target_id', 'audits__audit_log_entries', ['target_id'], unique=False)
    op.create_index('ix_audits__audit_log_entries_actor_id', 'audits__audit_log_entries', ['actor_id'], unique=False)
    op.create_index('ix_audits__audit_log_entries_account_id', 'audits__audit_log_entries', ['account_id'], unique=False)
    op.drop_column('audits__audit_log_entries', 'target_uid')
    op.drop_column('audits__audit_log_entries', 'account_uid')
    op.drop_column('audits__audit_log_entries', 'actor_uid')
    # ### end Alembic commands ###
