"""empty message

Revision ID: 28b72e13a4c0
Revises: eab1bae3cdab
Create Date: 2025-02-17 00:05:37.222144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b72e13a4c0'
down_revision: Union[str, None] = 'eab1bae3cdab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_search__terms_verified'), 'search__terms', ['verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search__terms_verified'), table_name='search__terms')
    # ### end Alembic commands ###
