"""empty message

Revision ID: 30fc212d61ac
Revises: 020ace687117
Create Date: 2025-02-22 17:27:56.481343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30fc212d61ac'
down_revision: Union[str, None] = '020ace687117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients__api_clients', sa.Column('permissions', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('search__search_records', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_search__search_records_client_id'), 'search__search_records', ['client_id'], unique=False)
    op.create_foreign_key(None, 'search__search_records', 'clients__api_clients', ['client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search__search_records', type_='foreignkey')
    op.drop_index(op.f('ix_search__search_records_client_id'), table_name='search__search_records')
    op.drop_column('search__search_records', 'client_id')
    op.drop_column('clients__api_clients', 'permissions')
    # ### end Alembic commands ###
