"""empty message

Revision ID: 57f6a18445f6
Revises: 2d518f59d3c3
Create Date: 2024-11-24 14:09:33.676854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f6a18445f6'
down_revision: Union[str, None] = '2d518f59d3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts__client_access_keys', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('accounts__client_access_keys', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_accounts__client_access_keys_active'), 'accounts__client_access_keys', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts__client_access_keys_active'), table_name='accounts__client_access_keys')
    op.drop_column('accounts__client_access_keys', 'updated_at')
    op.drop_column('accounts__client_access_keys', 'active')
    # ### end Alembic commands ###
