"""empty message

Revision ID: 5bc29eef72c0
Revises: 282bc349897c
Create Date: 2025-03-30 03:17:29.729751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc29eef72c0'
down_revision: Union[str, None] = '282bc349897c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes__questions',
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.ARRAY(sa.String(length=500)), nullable=False),
    sa.Column('correct_option', sa.String(length=500), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes__questions_id'), 'quizzes__questions', ['id'], unique=False)
    op.create_index(op.f('ix_quizzes__questions_is_deleted'), 'quizzes__questions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_quizzes__questions_uid'), 'quizzes__questions', ['uid'], unique=True)
    op.create_table('quizzes__question_to_topic_associations',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quizzes__questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['search__topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'topic_id')
    )
    op.create_index(op.f('ix_quizzes__question_to_topic_associations_id'), 'quizzes__question_to_topic_associations', ['id'], unique=False)
    op.create_index(op.f('ix_quizzes__question_to_topic_associations_question_id'), 'quizzes__question_to_topic_associations', ['question_id'], unique=False)
    op.create_index(op.f('ix_quizzes__question_to_topic_associations_topic_id'), 'quizzes__question_to_topic_associations', ['topic_id'], unique=False)
    op.create_table('quizzes__quizzes',
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['accounts__client_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'created_by_id')
    )
    op.create_index(op.f('ix_quizzes__quizzes_created_by_id'), 'quizzes__quizzes', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_quizzes__quizzes_id'), 'quizzes__quizzes', ['id'], unique=False)
    op.create_index(op.f('ix_quizzes__quizzes_is_deleted'), 'quizzes__quizzes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_quizzes__quizzes_name'), 'quizzes__quizzes', ['name'], unique=False)
    op.create_index(op.f('ix_quizzes__quizzes_uid'), 'quizzes__quizzes', ['uid'], unique=True)
    op.create_table('quizzes__question_to_quiz_associations',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quizzes__questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes__quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'quiz_id')
    )
    op.create_index(op.f('ix_quizzes__question_to_quiz_associations_id'), 'quizzes__question_to_quiz_associations', ['id'], unique=False)
    op.create_index(op.f('ix_quizzes__question_to_quiz_associations_question_id'), 'quizzes__question_to_quiz_associations', ['question_id'], unique=False)
    op.create_index(op.f('ix_quizzes__question_to_quiz_associations_quiz_id'), 'quizzes__question_to_quiz_associations', ['quiz_id'], unique=False)
    op.create_table('quizzes__question_to_term_associations',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quizzes__questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['search__terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'term_id')
    )
    op.create_index(op.f('ix_quizzes__question_to_term_associations_id'), 'quizzes__question_to_term_associations', ['id'], unique=False)
    op.create_index(op.f('ix_quizzes__question_to_term_associations_question_id'), 'quizzes__question_to_term_associations', ['question_id'], unique=False)
    op.create_index(op.f('ix_quizzes__question_to_term_associations_term_id'), 'quizzes__question_to_term_associations', ['term_id'], unique=False)
    op.create_table('quizzes__quiz_attempts',
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('attempted_by_id', sa.UUID(), nullable=False),
    sa.Column('attempted_questions', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['attempted_by_id'], ['accounts__client_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes__quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes__quiz_attempts_attempted_by_id'), 'quizzes__quiz_attempts', ['attempted_by_id'], unique=False)
    op.create_index(op.f('ix_quizzes__quiz_attempts_id'), 'quizzes__quiz_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_quizzes__quiz_attempts_quiz_id'), 'quizzes__quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quizzes__quiz_attempts_score'), 'quizzes__quiz_attempts', ['score'], unique=False)
    op.create_index(op.f('ix_quizzes__quiz_attempts_uid'), 'quizzes__quiz_attempts', ['uid'], unique=True)
    op.create_table('quizzes__quiz_attempt_question_answers',
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('answer_index', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('quiz_attempt_id', sa.Integer(), nullable=False),
    sa.Column('answered_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['answered_by_id'], ['accounts__client_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['quizzes__questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quizzes__quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes__quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'quiz_id', 'quiz_attempt_id', 'answered_by_id')
    )
    op.create_index('ix_quiz_attempt_quiz_id_created_at', 'quizzes__quiz_attempt_question_answers', ['quiz_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_quizzes__quiz_attempt_question_answers_answered_by_id'), 'quizzes__quiz_attempt_question_answers', ['answered_by_id'], unique=False)
    op.create_index(op.f('ix_quizzes__quiz_attempt_question_answers_correct'), 'quizzes__quiz_attempt_question_answers', ['correct'], unique=False)
    op.create_index(op.f('ix_quizzes__quiz_attempt_question_answers_id'), 'quizzes__quiz_attempt_question_answers', ['id'], unique=False)
    op.create_index(op.f('ix_quizzes__quiz_attempt_question_answers_question_id'), 'quizzes__quiz_attempt_question_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_quizzes__quiz_attempt_question_answers_quiz_attempt_id'), 'quizzes__quiz_attempt_question_answers', ['quiz_attempt_id'], unique=False)
    op.create_index(op.f('ix_quizzes__quiz_attempt_question_answers_quiz_id'), 'quizzes__quiz_attempt_question_answers', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quizzes__quiz_attempt_question_answers_uid'), 'quizzes__quiz_attempt_question_answers', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizzes__quiz_attempt_question_answers_uid'), table_name='quizzes__quiz_attempt_question_answers')
    op.drop_index(op.f('ix_quizzes__quiz_attempt_question_answers_quiz_id'), table_name='quizzes__quiz_attempt_question_answers')
    op.drop_index(op.f('ix_quizzes__quiz_attempt_question_answers_quiz_attempt_id'), table_name='quizzes__quiz_attempt_question_answers')
    op.drop_index(op.f('ix_quizzes__quiz_attempt_question_answers_question_id'), table_name='quizzes__quiz_attempt_question_answers')
    op.drop_index(op.f('ix_quizzes__quiz_attempt_question_answers_id'), table_name='quizzes__quiz_attempt_question_answers')
    op.drop_index(op.f('ix_quizzes__quiz_attempt_question_answers_correct'), table_name='quizzes__quiz_attempt_question_answers')
    op.drop_index(op.f('ix_quizzes__quiz_attempt_question_answers_answered_by_id'), table_name='quizzes__quiz_attempt_question_answers')
    op.drop_index('ix_quiz_attempt_quiz_id_created_at', table_name='quizzes__quiz_attempt_question_answers')
    op.drop_table('quizzes__quiz_attempt_question_answers')
    op.drop_index(op.f('ix_quizzes__quiz_attempts_uid'), table_name='quizzes__quiz_attempts')
    op.drop_index(op.f('ix_quizzes__quiz_attempts_score'), table_name='quizzes__quiz_attempts')
    op.drop_index(op.f('ix_quizzes__quiz_attempts_quiz_id'), table_name='quizzes__quiz_attempts')
    op.drop_index(op.f('ix_quizzes__quiz_attempts_id'), table_name='quizzes__quiz_attempts')
    op.drop_index(op.f('ix_quizzes__quiz_attempts_attempted_by_id'), table_name='quizzes__quiz_attempts')
    op.drop_table('quizzes__quiz_attempts')
    op.drop_index(op.f('ix_quizzes__question_to_term_associations_term_id'), table_name='quizzes__question_to_term_associations')
    op.drop_index(op.f('ix_quizzes__question_to_term_associations_question_id'), table_name='quizzes__question_to_term_associations')
    op.drop_index(op.f('ix_quizzes__question_to_term_associations_id'), table_name='quizzes__question_to_term_associations')
    op.drop_table('quizzes__question_to_term_associations')
    op.drop_index(op.f('ix_quizzes__question_to_quiz_associations_quiz_id'), table_name='quizzes__question_to_quiz_associations')
    op.drop_index(op.f('ix_quizzes__question_to_quiz_associations_question_id'), table_name='quizzes__question_to_quiz_associations')
    op.drop_index(op.f('ix_quizzes__question_to_quiz_associations_id'), table_name='quizzes__question_to_quiz_associations')
    op.drop_table('quizzes__question_to_quiz_associations')
    op.drop_index(op.f('ix_quizzes__quizzes_uid'), table_name='quizzes__quizzes')
    op.drop_index(op.f('ix_quizzes__quizzes_name'), table_name='quizzes__quizzes')
    op.drop_index(op.f('ix_quizzes__quizzes_is_deleted'), table_name='quizzes__quizzes')
    op.drop_index(op.f('ix_quizzes__quizzes_id'), table_name='quizzes__quizzes')
    op.drop_index(op.f('ix_quizzes__quizzes_created_by_id'), table_name='quizzes__quizzes')
    op.drop_table('quizzes__quizzes')
    op.drop_index(op.f('ix_quizzes__question_to_topic_associations_topic_id'), table_name='quizzes__question_to_topic_associations')
    op.drop_index(op.f('ix_quizzes__question_to_topic_associations_question_id'), table_name='quizzes__question_to_topic_associations')
    op.drop_index(op.f('ix_quizzes__question_to_topic_associations_id'), table_name='quizzes__question_to_topic_associations')
    op.drop_table('quizzes__question_to_topic_associations')
    op.drop_index(op.f('ix_quizzes__questions_uid'), table_name='quizzes__questions')
    op.drop_index(op.f('ix_quizzes__questions_is_deleted'), table_name='quizzes__questions')
    op.drop_index(op.f('ix_quizzes__questions_id'), table_name='quizzes__questions')
    op.drop_table('quizzes__questions')
    # ### end Alembic commands ###
