"""empty message

Revision ID: 5ede32348981
Revises: 578825331e6f
Create Date: 2024-12-23 19:23:35.629495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ede32348981'
down_revision: Union[str, None] = '578825331e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search__account_search_metrics_account_id', table_name='search__account_search_metrics')
    op.drop_index('ix_search__account_search_metrics_id', table_name='search__account_search_metrics')
    op.drop_index('ix_search__account_search_metrics_uid', table_name='search__account_search_metrics')
    op.drop_table('search__account_search_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search__account_search_metrics',
    sa.Column('uid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('search_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('most_searched_queries', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('most_searched_topics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts__client_accounts.id'], name='search__account_search_metrics_account_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='search__account_search_metrics_pkey')
    )
    op.create_index('ix_search__account_search_metrics_uid', 'search__account_search_metrics', ['uid'], unique=True)
    op.create_index('ix_search__account_search_metrics_id', 'search__account_search_metrics', ['id'], unique=False)
    op.create_index('ix_search__account_search_metrics_account_id', 'search__account_search_metrics', ['account_id'], unique=True)
    # ### end Alembic commands ###
