"""empty message

Revision ID: 65c9ec96b329
Revises: 77be52d92948
Create Date: 2025-02-23 00:48:39.039137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c9ec96b329'
down_revision: Union[str, None] = '77be52d92948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clients__api_clients_client_type'), 'clients__api_clients', ['client_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients__api_clients_client_type'), table_name='clients__api_clients')
    # ### end Alembic commands ###
