"""empty message

Revision ID: 6e9c404176a0
Revises: ac7b2125d976
Create Date: 2025-02-28 21:58:17.905601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9c404176a0'
down_revision: Union[str, None] = 'ac7b2125d976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients__api_clients_account_id_name_key', 'clients__api_clients', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('clients__api_clients_account_id_name_key', 'clients__api_clients', ['account_id', 'name'])
    # ### end Alembic commands ###
