"""empty message

Revision ID: 7a7ea1467e4d
Revises: 65ddd780f0bb
Create Date: 2025-04-12 18:17:27.955793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7ea1467e4d'
down_revision: Union[str, None] = '65ddd780f0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes__quiz_attempt_question_answers', sa.Column('is_final', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_quizzes__quiz_attempt_question_answers_is_final'), 'quizzes__quiz_attempt_question_answers', ['is_final'], unique=False)
    op.alter_column('quizzes__quizzes', 'duration',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes__quizzes', 'duration',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_quizzes__quiz_attempt_question_answers_is_final'), table_name='quizzes__quiz_attempt_question_answers')
    op.drop_column('quizzes__quiz_attempt_question_answers', 'is_final')
    # ### end Alembic commands ###
