"""empty message

Revision ID: 7e00c382aa6a
Revises: 65c9ec96b329
Create Date: 2025-02-23 00:50:07.208092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e00c382aa6a'
down_revision: Union[str, None] = '65c9ec96b329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients__api_clients', 'client_type',
               existing_type=postgresql.ENUM('INTERNAL', 'PARTNER', 'USER', name='clienttype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients__api_clients', 'client_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('INTERNAL', 'PARTNER', 'USER', name='clienttype'),
               existing_nullable=False)
    # ### end Alembic commands ###
