"""empty message

Revision ID: 8efe442db15e
Revises: 7a7ea1467e4d
Create Date: 2025-04-13 22:01:11.748621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efe442db15e'
down_revision: Union[str, None] = '7a7ea1467e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quizzes__quiz_attempt_questio_question_id_quiz_id_quiz_atte_key', 'quizzes__quiz_attempt_question_answers', type_='unique')
    op.create_unique_constraint('uq_quiz_attempt_question_answer', 'quizzes__quiz_attempt_question_answers', ['question_id', 'quiz_attempt_id', 'answered_by_id'])
    op.add_column('quizzes__quiz_attempts', sa.Column('duration', sa.Float(precision=2), nullable=True))
    op.add_column('quizzes__quizzes', sa.Column('questions_count', sa.Integer(), nullable=False))
    op.alter_column('quizzes__quizzes', 'duration',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes__quizzes', 'duration',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('quizzes__quizzes', 'questions_count')
    op.drop_column('quizzes__quiz_attempts', 'duration')
    op.drop_constraint('uq_quiz_attempt_question_answer', 'quizzes__quiz_attempt_question_answers', type_='unique')
    op.create_unique_constraint('quizzes__quiz_attempt_questio_question_id_quiz_id_quiz_atte_key', 'quizzes__quiz_attempt_question_answers', ['question_id', 'quiz_id', 'quiz_attempt_id', 'answered_by_id'])
    # ### end Alembic commands ###
