"""empty message

Revision ID: a41dfa1e5a18
Revises: 4c25385e9556
Create Date: 2024-11-26 15:14:40.127748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41dfa1e5a18'
down_revision: Union[str, None] = '4c25385e9556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts__client_access_keys', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index('ix_accounts__client_access_keys_active', table_name='accounts__client_access_keys')
    op.create_index(op.f('ix_accounts__client_access_keys_is_active'), 'accounts__client_access_keys', ['is_active'], unique=False)
    op.drop_column('accounts__client_access_keys', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts__client_access_keys', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_accounts__client_access_keys_is_active'), table_name='accounts__client_access_keys')
    op.create_index('ix_accounts__client_access_keys_active', 'accounts__client_access_keys', ['active'], unique=False)
    op.drop_column('accounts__client_access_keys', 'is_active')
    # ### end Alembic commands ###
