"""empty message

Revision ID: aafaae310ce0
Revises: bf3c9de3bb7f
Create Date: 2025-02-19 00:29:44.133013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aafaae310ce0'
down_revision: Union[str, None] = 'bf3c9de3bb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search__search_records', sa.Column('query_tsvector', postgresql.TSVECTOR(), nullable=True))
    op.create_index(op.f('ix_search__search_records_query_tsvector'), 'search__search_records', ['query_tsvector'], unique=False)
    op.create_index('ix_search_records_query_tsvector', 'search__search_records', ['query_tsvector'], unique=False, postgresql_using='gin')
    op.add_column('search__terms', sa.Column('definition_tsvector', postgresql.TSVECTOR(), nullable=True))
    op.add_column('search__terms', sa.Column('source_id', sa.Integer(), nullable=True))
    op.drop_index('ix_search__terms_source_name', table_name='search__terms')
    op.create_index(op.f('ix_search__terms_definition_tsvector'), 'search__terms', ['definition_tsvector'], unique=False)
    op.create_index(op.f('ix_search__terms_source_id'), 'search__terms', ['source_id'], unique=False)
    op.create_index('ix_terms_definition_tsvector', 'search__terms', ['definition_tsvector'], unique=False, postgresql_using='gin')
    op.create_unique_constraint(None, 'search__terms', ['name', 'source_id'])
    op.create_foreign_key(None, 'search__terms', 'search__term_sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.drop_column('search__terms', 'source_url')
    op.drop_column('search__terms', 'source_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search__terms', sa.Column('source_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('search__terms', sa.Column('source_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'search__terms', type_='foreignkey')
    op.drop_constraint(None, 'search__terms', type_='unique')
    op.drop_index('ix_terms_definition_tsvector', table_name='search__terms', postgresql_using='gin')
    op.drop_index(op.f('ix_search__terms_source_id'), table_name='search__terms')
    op.drop_index(op.f('ix_search__terms_definition_tsvector'), table_name='search__terms')
    op.create_index('ix_search__terms_source_name', 'search__terms', ['source_name'], unique=False)
    op.drop_column('search__terms', 'source_id')
    op.drop_column('search__terms', 'definition_tsvector')
    op.drop_index('ix_search_records_query_tsvector', table_name='search__search_records', postgresql_using='gin')
    op.drop_index(op.f('ix_search__search_records_query_tsvector'), table_name='search__search_records')
    op.drop_column('search__search_records', 'query_tsvector')
    # ### end Alembic commands ###
