"""empty message

Revision ID: ac7b2125d976
Revises: cf228ea68de6
Create Date: 2025-02-28 19:09:56.577283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7b2125d976'
down_revision: Union[str, None] = 'cf228ea68de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients__api_keys_active', table_name='clients__api_keys')
    op.drop_column('clients__api_keys', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients__api_keys', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_clients__api_keys_active', 'clients__api_keys', ['active'], unique=False)
    # ### end Alembic commands ###
