"""empty message

Revision ID: beabaa47d346
Revises: e83f05dfc9a7
Create Date: 2025-03-03 22:34:09.098767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'beabaa47d346'
down_revision: Union[str, None] = 'e83f05dfc9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits__audit_log_entries', sa.Column('user_agent', sa.String(length=255), nullable=True))
    op.add_column('audits__audit_log_entries', sa.Column('ip_address', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True))
    op.drop_index('ix_audits__audit_log_entries_source', table_name='audits__audit_log_entries')
    op.create_index(op.f('ix_audits__audit_log_entries_ip_address'), 'audits__audit_log_entries', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audits__audit_log_entries_user_agent'), 'audits__audit_log_entries', ['user_agent'], unique=False)
    op.drop_column('audits__audit_log_entries', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits__audit_log_entries', sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_audits__audit_log_entries_user_agent'), table_name='audits__audit_log_entries')
    op.drop_index(op.f('ix_audits__audit_log_entries_ip_address'), table_name='audits__audit_log_entries')
    op.create_index('ix_audits__audit_log_entries_source', 'audits__audit_log_entries', ['source'], unique=False)
    op.drop_column('audits__audit_log_entries', 'ip_address')
    op.drop_column('audits__audit_log_entries', 'user_agent')
    # ### end Alembic commands ###
