"""empty message

Revision ID: bfb0f184ace1
Revises: 5bc29eef72c0
Create Date: 2025-03-30 19:32:14.423432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb0f184ace1'
down_revision: Union[str, None] = '5bc29eef72c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients__api_clients', 'client_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index('ix_api_clients_client_type_account_id', 'clients__api_clients', ['client_type', 'account_id'], unique=False)
    op.create_index(op.f('ix_quizzes__questions_difficulty'), 'quizzes__questions', ['difficulty'], unique=False)
    op.drop_index('ix_quiz_attempt_quiz_id_created_at', table_name='quizzes__quiz_attempt_question_answers')
    op.create_index('ix_quiz_atmpt_questn_answr_questn_id_quiz_atmpt_id_answrd_by_id', 'quizzes__quiz_attempt_question_answers', ['question_id', 'quiz_attempt_id', 'answered_by_id'], unique=False)
    op.create_index('ix_quiz_atmpt_questn_answr_quiz_questn_answrd_by_id_ctd_at', 'quizzes__quiz_attempt_question_answers', ['quiz_id', 'question_id', 'answered_by_id', 'created_at'], unique=False)
    op.create_index('ix_quiz_attempt_question_answer_created_at', 'quizzes__quiz_attempt_question_answers', ['created_at'], unique=False)
    op.create_index('ix_quiz_attempt_created_at', 'quizzes__quiz_attempts', ['created_at'], unique=False)
    op.create_index('ix_quiz_attempt_quiz_id_attempted_by_id', 'quizzes__quiz_attempts', ['quiz_id', 'attempted_by_id'], unique=False)
    op.create_index('ix_quiz_created_at', 'quizzes__quizzes', ['created_at'], unique=False)
    op.create_index('ix_quiz_updated_at', 'quizzes__quizzes', ['updated_at'], unique=False)
    op.create_index(op.f('ix_quizzes__quizzes_difficulty'), 'quizzes__quizzes', ['difficulty'], unique=False)
    op.create_index(op.f('ix_search__term_sources_is_deleted'), 'search__term_sources', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search__term_sources_is_deleted'), table_name='search__term_sources')
    op.drop_index(op.f('ix_quizzes__quizzes_difficulty'), table_name='quizzes__quizzes')
    op.drop_index('ix_quiz_updated_at', table_name='quizzes__quizzes')
    op.drop_index('ix_quiz_created_at', table_name='quizzes__quizzes')
    op.drop_index('ix_quiz_attempt_quiz_id_attempted_by_id', table_name='quizzes__quiz_attempts')
    op.drop_index('ix_quiz_attempt_created_at', table_name='quizzes__quiz_attempts')
    op.drop_index('ix_quiz_attempt_question_answer_created_at', table_name='quizzes__quiz_attempt_question_answers')
    op.drop_index('ix_quiz_atmpt_questn_answr_quiz_questn_answrd_by_id_ctd_at', table_name='quizzes__quiz_attempt_question_answers')
    op.drop_index('ix_quiz_atmpt_questn_answr_questn_id_quiz_atmpt_id_answrd_by_id', table_name='quizzes__quiz_attempt_question_answers')
    op.create_index('ix_quiz_attempt_quiz_id_created_at', 'quizzes__quiz_attempt_question_answers', ['quiz_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_quizzes__questions_difficulty'), table_name='quizzes__questions')
    op.drop_index('ix_api_clients_client_type_account_id', table_name='clients__api_clients')
    op.alter_column('clients__api_clients', 'client_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
