"""empty message

Revision ID: cf228ea68de6
Revises: 37f2fd242160
Create Date: 2025-02-25 00:18:54.621405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf228ea68de6'
down_revision: Union[str, None] = '37f2fd242160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients__api_clients', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_clients__api_clients_created_by_id'), 'clients__api_clients', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'clients__api_clients', 'accounts__client_accounts', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients__api_clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients__api_clients_created_by_id'), table_name='clients__api_clients')
    op.drop_column('clients__api_clients', 'created_by_id')
    # ### end Alembic commands ###
