"""empty message

Revision ID: d7767ddcca25
Revises: 70e78a2088f3
Create Date: 2025-04-19 00:45:04.593116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7767ddcca25'
down_revision: Union[str, None] = '70e78a2088f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits__audit_log_entries', sa.Column('extradata', sa.JSON(), nullable=True))
    op.drop_column('audits__audit_log_entries', 'data')
    op.alter_column('quizzes__quiz_attempts', 'duration',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('quizzes__quizzes', 'duration',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes__quizzes', 'duration',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('quizzes__quiz_attempts', 'duration',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.add_column('audits__audit_log_entries', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('audits__audit_log_entries', 'extradata')
    # ### end Alembic commands ###
