"""empty message

Revision ID: d852c52f0674
Revises: 754b0bb0f202
Create Date: 2024-12-15 08:52:51.754271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd852c52f0674'
down_revision: Union[str, None] = '754b0bb0f202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search__terminologies_id', table_name='search__terminologies')
    op.drop_index('ix_search__terminologies_name', table_name='search__terminologies')
    op.drop_index('ix_search__terminologies_uid', table_name='search__terminologies')
    op.drop_table('search__terminologies')
    op.add_column('search__search_records', sa.Column('topics', sa.ARRAY(sa.String(length=50), dimensions=1), nullable=True))
    op.add_column('search__search_records', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_search__search_records_made_at', table_name='search__search_records')
    op.create_index(op.f('ix_search__search_records_timestamp'), 'search__search_records', ['timestamp'], unique=False)
    op.drop_column('search__search_records', 'made_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search__search_records', sa.Column('made_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_search__search_records_timestamp'), table_name='search__search_records')
    op.create_index('ix_search__search_records_made_at', 'search__search_records', ['made_at'], unique=False)
    op.drop_column('search__search_records', 'timestamp')
    op.drop_column('search__search_records', 'topics')
    op.create_table('search__terminologies',
    sa.Column('uid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('definition', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=True),
    sa.Column('grammatical_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='search__terminologies_pkey')
    )
    op.create_index('ix_search__terminologies_uid', 'search__terminologies', ['uid'], unique=True)
    op.create_index('ix_search__terminologies_name', 'search__terminologies', ['name'], unique=False)
    op.create_index('ix_search__terminologies_id', 'search__terminologies', ['id'], unique=False)
    # ### end Alembic commands ###
