"""empty message

Revision ID: eab1bae3cdab
Revises: 64bba2220099
Create Date: 2025-02-16 19:45:27.274453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab1bae3cdab'
down_revision: Union[str, None] = '64bba2220099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'search__term_to_topic_associations', ['term_id', 'topic_id'])
    op.alter_column('search__terms', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('search__topics', 'description',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search__topics', 'description',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    op.alter_column('search__terms', 'name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'search__term_to_topic_associations', type_='unique')
    # ### end Alembic commands ###
