"""empty message

Revision ID: f0ffd6e7e801
Revises: 09a700243f83
Create Date: 2025-04-09 20:54:04.019730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0ffd6e7e801'
down_revision: Union[str, None] = '09a700243f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes__questions', sa.Column('search_tsvector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_question_created_at', 'quizzes__questions', ['created_at'], unique=False)
    op.create_index('ix_question_search_tsvector', 'quizzes__questions', ['search_tsvector'], unique=False, postgresql_using='gin')
    op.add_column('quizzes__quizzes', sa.Column('search_tsvector', postgresql.TSVECTOR(), nullable=True))
    op.alter_column('quizzes__quizzes', 'duration',
               existing_type=sa.INTEGER(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.create_index('ix_quiz_search_tsvector', 'quizzes__quizzes', ['search_tsvector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_quizzes__quizzes_duration'), 'quizzes__quizzes', ['duration'], unique=False)
    op.drop_index('ix_search__search_records_query_tsvector', table_name='search__search_records')
    op.drop_index('ix_search__terms_search_tsvector', table_name='search__terms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_search__terms_search_tsvector', 'search__terms', ['search_tsvector'], unique=False)
    op.create_index('ix_search__search_records_query_tsvector', 'search__search_records', ['query_tsvector'], unique=False)
    op.drop_index(op.f('ix_quizzes__quizzes_duration'), table_name='quizzes__quizzes')
    op.drop_index('ix_quiz_search_tsvector', table_name='quizzes__quizzes', postgresql_using='gin')
    op.alter_column('quizzes__quizzes', 'duration',
               existing_type=sa.Float(precision=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('quizzes__quizzes', 'search_tsvector')
    op.drop_index('ix_question_search_tsvector', table_name='quizzes__questions', postgresql_using='gin')
    op.drop_index('ix_question_created_at', table_name='quizzes__questions')
    op.drop_column('quizzes__questions', 'search_tsvector')
    # ### end Alembic commands ###
